
version: 2
jobs:
  build:
    docker:
      -image: node
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t n2048/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push n2048/$IMAGE_NAME:$TAG
      
  deploy:
    machine: true
    steps:
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "docker pull n2048/$IMAGE_NAME:$TAG"
  

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy